const level1 = new Level(
    [
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new SmallChicken(),
        new SmallChicken(),
        new SmallChicken(),
        new SmallChicken(),
        new Endboss()
    ],
    [
        new Cloud('img/5_background/layers/4_clouds/1.png', 15, 0.15),
        new Cloud('img/5_background/layers/4_clouds/2.png', 20, 0.25),
    ],
    [
        new BackgroundObject('img/5_background/layers/air.png', -719),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', -719),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', -719),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', -719),
        new BackgroundObject('img/5_background/layers/air.png', 0),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/air.png', 719),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719),
        new BackgroundObject('img/5_background/layers/air.png', 719 * 2),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719 * 2),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719 * 2),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719 * 2),
        new BackgroundObject('img/5_background/layers/air.png', 719 * 3),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719 * 3),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719 * 3),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719 * 3),
        new BackgroundObject('img/5_background/layers/air.png', 719 * 4),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719 * 4),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719 * 4),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719 * 4),
    ],
    [
        new Bottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 1500, 340),
        new Bottle('img/6_salsa_bottle/salsa_bottle.png', 1500, 110),
        new Bottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 1500, 340),
        new Bottle('img/6_salsa_bottle/salsa_bottle.png', 1500, 70),   
        new Bottle('img/6_salsa_bottle/salsa_bottle.png', 2000, 80),
        new Bottle('img/6_salsa_bottle/salsa_bottle.png', 2000, 100),
        new Bottle('img/6_salsa_bottle/2_salsa_bottle_on_ground.png', 2000, 330),
    ],
    [
        new Coin('img/8_coin/coin_1.png', 110, 120),
        new Coin('img/8_coin/coin_1.png', 150, 100),
        new Coin('img/8_coin/coin_1.png', 190, 80),
        new Coin('img/8_coin/coin_1.png', 230, 60),
        new Coin('img/8_coin/coin_1.png', 270, 80),
        new Coin('img/8_coin/coin_1.png', 310, 100),
        new Coin('img/8_coin/coin_1.png', 350, 120),
        new Coin('img/8_coin/coin_1.png', 1000, 180),
        new Coin('img/8_coin/coin_1.png', 1200, 180),
        new Coin('img/8_coin/coin_1.png', 1400, 180),
    ]
);