const level1 = new Level (
    [
        new Chicken(),
        new SmallChicken(),
        new Chicken(),
        new SmallChicken(),
        new Chicken(),
        new Chicken(),
        new SmallChicken(),
        new Endboss()
    ],
    [
        new Cloud('img/5_background/layers/4_clouds/1.png', 15, 0.15),
        new Cloud('img/5_background/layers/4_clouds/2.png', 20, 0.25),
    ],
    [
        new BackgroundObject('img/5_background/layers/air.png', -719),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', -719),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', -719),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', -719),
        new BackgroundObject('img/5_background/layers/air.png', 0),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/air.png', 719),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719),
        new BackgroundObject('img/5_background/layers/air.png', 719 * 2),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719 * 2),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719 * 2),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719 * 2),
        new BackgroundObject('img/5_background/layers/air.png', 719 * 3),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719 * 3),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719 * 3),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719 * 3),
        new BackgroundObject('img/5_background/layers/air.png', 719 * 4),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719 * 4),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719 * 4),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719 * 4),
    ],
    [
        new Bottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 340),
        new Bottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 340),
        new Bottle('img/6_salsa_bottle/2_salsa_bottle_on_ground.png', 330),
        new Bottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 340),
        new Bottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 340),
        new Bottle('img/6_salsa_bottle/2_salsa_bottle_on_ground.png', 330),
        new Bottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 340),
        new Bottle('img/6_salsa_bottle/2_salsa_bottle_on_ground.png', 340),
        new Bottle('img/6_salsa_bottle/2_salsa_bottle_on_ground.png', 330),
        new Bottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 340),
        new Bottle('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 340),
    ]
);