class CharakterImg {

    IMAGES_WALKING;
    IMAGES_JUMPING;
    IMAGES_HURT;
    IMAGES_DEAD;
    IMAGES_IDLE_SHORT;
    IMAGES_IDLE_LONG;
    
    constructor (IMAGES_WALKING, IMAGES_JUMPING, IMAGES_HURT, IMAGES_DEAD, IMAGES_IDLE_SHORT, IMAGES_IDLE_LONG) {
        this.IMAGES_WALKING = IMAGES_WALKING;
        this.IMAGES_JUMPING = IMAGES_JUMPING;
        this.IMAGES_HURT = IMAGES_HURT;
        this.IMAGES_DEAD = IMAGES_DEAD;
        this.IMAGES_IDLE_SHORT = IMAGES_IDLE_SHORT;
        this.IMAGES_IDLE_LONG = IMAGES_IDLE_LONG;
    }
}